### PR TITLE
add client close frame

### PR DESCRIPTION
**Pull request by Alarmfifa**
An old realization of ws client was cause of exception in server part in time of disconnecting.
Add right code for correct disconnecting.

### CODE REVIEW

**Comment by Alarmfifa** [comment]
@dominics, hello!
I missed notification =( Sorry for a long answer.
If I understood you, you propose to rewrite method something like this:
```(php)
    public function disconnect()
    {
    	$frame = new HybiFrame();
    	$payload = $this->protocol->getPayload();
        $frame->encode($payload, Protocol::TYPE_CLOSE, $masked = true );
		
        if ($this->socket) {
            $this->socket->send($frame->getFrameBuffer());
            $this->socket->disconnect();
        }
        $this->connected = false;
    }
```
It works, but it isn't perfect, because the client doesn't wait and receive close frame from the server and closes socket =(
>debug: Wrench\ConnectionManager: Wrench\Connection: ::1:58321 (3cab20014682a5b544f17a03d4d6c814260b9f4b75a4ccb538a01c140974657dfb5489d188dffb0be9c2de27c92df32b24500dc63a1b0c7c60d30c254ac88ac8): Handling payload: 
notice: Wrench\ConnectionManager: Wrench\Connection: ::1:58321 (3cab20014682a5b544f17a03d4d6c814260b9f4b75a4ccb538a01c140974657dfb5489d188dffb0be9c2de27c92df32b24500dc63a1b0c7c60d30c254ac88ac8): Close frame received
warning: Wrench\ConnectionManager: Wrench\Connection: ::1:58321 (3cab20014682a5b544f17a03d4d6c814260b9f4b75a4ccb538a01c140974657dfb5489d188dffb0be9c2de27c92df32b24500dc63a1b0c7c60d30c254ac88ac8): Unable to send close message
info: Wrench\ConnectionManager: Wrench\Connection: ::1:58321 (3cab20014682a5b544f17a03d4d6c814260b9f4b75a4ccb538a01c140974657dfb5489d188dffb0be9c2de27c92df32b24500dc63a1b0c7c60d30c254ac88ac8): Disconnected
 
But I think, that this solution is better, than nothing.
What do you think? I can make another pull request.

**Comment by dominics** [comment]
> you propose to rewrite method something like this

Yup, that's much much better - would be happy to merge that or something similar.

We'd probably still put the close reason in the frame though (it seems to have gone missing from that example - the `$payload = $this->protocol->getPayload();` is empty?)

I think a separate PR would be best, yeah.

**Comment by Alarmfifa** [comment]
@dominics, In my example yes, payload is empty:
```php
class Wrench\Payload\HybiPayload#8 (1) {
  protected $frames =>
  array(0) {
  }
}
```
I've fixed a pull request.

**Comment by dominics** [comment]
Hey @Alarmfifa, I've decided to continue this PR in #51 - I've added a bit to your changes.

**Pull request closed without merging**
