### PR TITLE
Fixed null given to fread

### PR DESCRIPTION
**Pull request by DaSpors**

### CODE REVIEW

**Comment by dominics** [comment]
Hey, thanks for the patch.

But I was wondering if you have ever seen this condition occur? There are only four places in the codebase that write to `$this->socket`, and I'd be interested to know which was passing an invalid socket resource. (It'd be even better to have a test, of course, but I can write that if you can point me in the right direction to reproduce the failure).

What I mean is that, PHP does this on `fread` with an invalid socket:

```
$ php <<< '<?php var_dump(fread(false, 100));'

Warning: fread() expects parameter 1 to be resource, boolean given in - on line 1

Call Stack:
    0.0001     231416   1. {main}() -:0
    0.0001     231560   2. fread() -:1

bool(false)
```

The fact that it returns false for this case (and other falsey values I checked like `null`, `[]`) means the contents of this `if` branch you're adding will never be hit, right?

Double-check my thinking on that, and if you can come up with some situation where it would be, I'll merge this. As it is, I can put `exit(1)` inside the `if` branch, and the test suite still passes! (Just indicates it doesn't occur with our admittedly low-coverage test suite, but still.)

**Comment by dominics** [comment]
Aha! I gotcha now! :D

**Comment by DaSpors** [comment]
Fixed my Fix :)
Had this in some rare cases where PHP runs in CLI, forked itself to background and runs for some days. Maybe it has to do with port-overflow or something like that. Seem to be really low level but i think as it is now it cannot harm anything while still beeing on the safe side.

**Comment by dominics** [comment]
Looks good now. Tweaked it to make sure `->connected` was back to false.

Woo, thanks again. :tada:

**Pull request merged**
